// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	// this format is versioned
	Version int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// git hash of the revision from which Hercules is built
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// repository's name
	Repository string `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	// UNIX timestamp of the first analysed commit
	BeginUnixTime int64 `protobuf:"varint,4,opt,name=begin_unix_time,json=beginUnixTime,proto3" json:"begin_unix_time,omitempty"`
	// UNIX timestamp of the last analysed commit
	EndUnixTime int64 `protobuf:"varint,5,opt,name=end_unix_time,json=endUnixTime,proto3" json:"end_unix_time,omitempty"`
	// number of processed commits
	Commits int32 `protobuf:"varint,6,opt,name=commits,proto3" json:"commits,omitempty"`
	// duration of the analysis in milliseconds
	RunTime int64 `protobuf:"varint,7,opt,name=run_time,json=runTime,proto3" json:"run_time,omitempty"`
	// time taken by each pipeline item in seconds
	RunTimePerItem       map[string]float64 `protobuf:"bytes,8,rep,name=run_time_per_item,json=runTimePerItem,proto3" json:"run_time_per_item,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Metadata) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Metadata) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Metadata) GetBeginUnixTime() int64 {
	if m != nil {
		return m.BeginUnixTime
	}
	return 0
}

func (m *Metadata) GetEndUnixTime() int64 {
	if m != nil {
		return m.EndUnixTime
	}
	return 0
}

func (m *Metadata) GetCommits() int32 {
	if m != nil {
		return m.Commits
	}
	return 0
}

func (m *Metadata) GetRunTime() int64 {
	if m != nil {
		return m.RunTime
	}
	return 0
}

func (m *Metadata) GetRunTimePerItem() map[string]float64 {
	if m != nil {
		return m.RunTimePerItem
	}
	return nil
}

type BurndownSparseMatrixRow struct {
	// the first `len(column)` elements are stored,
	// the rest `number_of_columns - len(column)` values are zeros
	Columns              []uint32 `protobuf:"varint,1,rep,packed,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BurndownSparseMatrixRow) Reset()         { *m = BurndownSparseMatrixRow{} }
func (m *BurndownSparseMatrixRow) String() string { return proto.CompactTextString(m) }
func (*BurndownSparseMatrixRow) ProtoMessage()    {}
func (*BurndownSparseMatrixRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}
func (m *BurndownSparseMatrixRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurndownSparseMatrixRow.Unmarshal(m, b)
}
func (m *BurndownSparseMatrixRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurndownSparseMatrixRow.Marshal(b, m, deterministic)
}
func (m *BurndownSparseMatrixRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurndownSparseMatrixRow.Merge(m, src)
}
func (m *BurndownSparseMatrixRow) XXX_Size() int {
	return xxx_messageInfo_BurndownSparseMatrixRow.Size(m)
}
func (m *BurndownSparseMatrixRow) XXX_DiscardUnknown() {
	xxx_messageInfo_BurndownSparseMatrixRow.DiscardUnknown(m)
}

var xxx_messageInfo_BurndownSparseMatrixRow proto.InternalMessageInfo

func (m *BurndownSparseMatrixRow) GetColumns() []uint32 {
	if m != nil {
		return m.Columns
	}
	return nil
}

type BurndownSparseMatrix struct {
	Name            string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NumberOfRows    int32  `protobuf:"varint,2,opt,name=number_of_rows,json=numberOfRows,proto3" json:"number_of_rows,omitempty"`
	NumberOfColumns int32  `protobuf:"varint,3,opt,name=number_of_columns,json=numberOfColumns,proto3" json:"number_of_columns,omitempty"`
	// `len(row)` matches `number_of_rows`
	Rows                 []*BurndownSparseMatrixRow `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BurndownSparseMatrix) Reset()         { *m = BurndownSparseMatrix{} }
func (m *BurndownSparseMatrix) String() string { return proto.CompactTextString(m) }
func (*BurndownSparseMatrix) ProtoMessage()    {}
func (*BurndownSparseMatrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}
func (m *BurndownSparseMatrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurndownSparseMatrix.Unmarshal(m, b)
}
func (m *BurndownSparseMatrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurndownSparseMatrix.Marshal(b, m, deterministic)
}
func (m *BurndownSparseMatrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurndownSparseMatrix.Merge(m, src)
}
func (m *BurndownSparseMatrix) XXX_Size() int {
	return xxx_messageInfo_BurndownSparseMatrix.Size(m)
}
func (m *BurndownSparseMatrix) XXX_DiscardUnknown() {
	xxx_messageInfo_BurndownSparseMatrix.DiscardUnknown(m)
}

var xxx_messageInfo_BurndownSparseMatrix proto.InternalMessageInfo

func (m *BurndownSparseMatrix) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BurndownSparseMatrix) GetNumberOfRows() int32 {
	if m != nil {
		return m.NumberOfRows
	}
	return 0
}

func (m *BurndownSparseMatrix) GetNumberOfColumns() int32 {
	if m != nil {
		return m.NumberOfColumns
	}
	return 0
}

func (m *BurndownSparseMatrix) GetRows() []*BurndownSparseMatrixRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type FilesOwnership struct {
	// The sum always equals to the total number of lines in the file.
	Value                map[int32]int32 `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FilesOwnership) Reset()         { *m = FilesOwnership{} }
func (m *FilesOwnership) String() string { return proto.CompactTextString(m) }
func (*FilesOwnership) ProtoMessage()    {}
func (*FilesOwnership) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}
func (m *FilesOwnership) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesOwnership.Unmarshal(m, b)
}
func (m *FilesOwnership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesOwnership.Marshal(b, m, deterministic)
}
func (m *FilesOwnership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesOwnership.Merge(m, src)
}
func (m *FilesOwnership) XXX_Size() int {
	return xxx_messageInfo_FilesOwnership.Size(m)
}
func (m *FilesOwnership) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesOwnership.DiscardUnknown(m)
}

var xxx_messageInfo_FilesOwnership proto.InternalMessageInfo

func (m *FilesOwnership) GetValue() map[int32]int32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type BurndownAnalysisResults struct {
	// how many ticks are in each band [burndown_project, burndown_file, burndown_developer]
	Granularity int32 `protobuf:"varint,1,opt,name=granularity,proto3" json:"granularity,omitempty"`
	// how frequently we measure the state of each band [burndown_project, burndown_file, burndown_developer]
	Sampling int32 `protobuf:"varint,2,opt,name=sampling,proto3" json:"sampling,omitempty"`
	// always exists
	Project *BurndownSparseMatrix `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	// this is included if `--burndown-files` was specified
	Files []*BurndownSparseMatrix `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	// these two are included if `--burndown-people` was specified
	People []*BurndownSparseMatrix `protobuf:"bytes,5,rep,name=people,proto3" json:"people,omitempty"`
	// rows and cols order correspond to `burndown_developer`
	PeopleInteraction *CompressedSparseRowMatrix `protobuf:"bytes,6,opt,name=people_interaction,json=peopleInteraction,proto3" json:"people_interaction,omitempty"`
	// How many lines belong to relevant developers for each file. The order is the same as in `files`.
	FilesOwnership []*FilesOwnership `protobuf:"bytes,7,rep,name=files_ownership,json=filesOwnership,proto3" json:"files_ownership,omitempty"`
	// how long each tick is, as an int64 nanosecond count (Go's time.Duration)
	TickSize             int64    `protobuf:"varint,8,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BurndownAnalysisResults) Reset()         { *m = BurndownAnalysisResults{} }
func (m *BurndownAnalysisResults) String() string { return proto.CompactTextString(m) }
func (*BurndownAnalysisResults) ProtoMessage()    {}
func (*BurndownAnalysisResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}
func (m *BurndownAnalysisResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurndownAnalysisResults.Unmarshal(m, b)
}
func (m *BurndownAnalysisResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurndownAnalysisResults.Marshal(b, m, deterministic)
}
func (m *BurndownAnalysisResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurndownAnalysisResults.Merge(m, src)
}
func (m *BurndownAnalysisResults) XXX_Size() int {
	return xxx_messageInfo_BurndownAnalysisResults.Size(m)
}
func (m *BurndownAnalysisResults) XXX_DiscardUnknown() {
	xxx_messageInfo_BurndownAnalysisResults.DiscardUnknown(m)
}

var xxx_messageInfo_BurndownAnalysisResults proto.InternalMessageInfo

func (m *BurndownAnalysisResults) GetGranularity() int32 {
	if m != nil {
		return m.Granularity
	}
	return 0
}

func (m *BurndownAnalysisResults) GetSampling() int32 {
	if m != nil {
		return m.Sampling
	}
	return 0
}

func (m *BurndownAnalysisResults) GetProject() *BurndownSparseMatrix {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *BurndownAnalysisResults) GetFiles() []*BurndownSparseMatrix {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *BurndownAnalysisResults) GetPeople() []*BurndownSparseMatrix {
	if m != nil {
		return m.People
	}
	return nil
}

func (m *BurndownAnalysisResults) GetPeopleInteraction() *CompressedSparseRowMatrix {
	if m != nil {
		return m.PeopleInteraction
	}
	return nil
}

func (m *BurndownAnalysisResults) GetFilesOwnership() []*FilesOwnership {
	if m != nil {
		return m.FilesOwnership
	}
	return nil
}

func (m *BurndownAnalysisResults) GetTickSize() int64 {
	if m != nil {
		return m.TickSize
	}
	return 0
}

type CompressedSparseRowMatrix struct {
	NumberOfRows    int32 `protobuf:"varint,1,opt,name=number_of_rows,json=numberOfRows,proto3" json:"number_of_rows,omitempty"`
	NumberOfColumns int32 `protobuf:"varint,2,opt,name=number_of_columns,json=numberOfColumns,proto3" json:"number_of_columns,omitempty"`
	// https://en.wikipedia.org/wiki/Sparse_matrix#Compressed_sparse_row_.28CSR.2C_CRS_or_Yale_format.29
	Data                 []int64  `protobuf:"varint,3,rep,packed,name=data,proto3" json:"data,omitempty"`
	Indices              []int32  `protobuf:"varint,4,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	Indptr               []int64  `protobuf:"varint,5,rep,packed,name=indptr,proto3" json:"indptr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompressedSparseRowMatrix) Reset()         { *m = CompressedSparseRowMatrix{} }
func (m *CompressedSparseRowMatrix) String() string { return proto.CompactTextString(m) }
func (*CompressedSparseRowMatrix) ProtoMessage()    {}
func (*CompressedSparseRowMatrix) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}
func (m *CompressedSparseRowMatrix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompressedSparseRowMatrix.Unmarshal(m, b)
}
func (m *CompressedSparseRowMatrix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompressedSparseRowMatrix.Marshal(b, m, deterministic)
}
func (m *CompressedSparseRowMatrix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompressedSparseRowMatrix.Merge(m, src)
}
func (m *CompressedSparseRowMatrix) XXX_Size() int {
	return xxx_messageInfo_CompressedSparseRowMatrix.Size(m)
}
func (m *CompressedSparseRowMatrix) XXX_DiscardUnknown() {
	xxx_messageInfo_CompressedSparseRowMatrix.DiscardUnknown(m)
}

var xxx_messageInfo_CompressedSparseRowMatrix proto.InternalMessageInfo

func (m *CompressedSparseRowMatrix) GetNumberOfRows() int32 {
	if m != nil {
		return m.NumberOfRows
	}
	return 0
}

func (m *CompressedSparseRowMatrix) GetNumberOfColumns() int32 {
	if m != nil {
		return m.NumberOfColumns
	}
	return 0
}

func (m *CompressedSparseRowMatrix) GetData() []int64 {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CompressedSparseRowMatrix) GetIndices() []int32 {
	if m != nil {
		return m.Indices
	}
	return nil
}

func (m *CompressedSparseRowMatrix) GetIndptr() []int64 {
	if m != nil {
		return m.Indptr
	}
	return nil
}

type Couples struct {
	// name of each `matrix`'s row and column
	Index []string `protobuf:"bytes,1,rep,name=index,proto3" json:"index,omitempty"`
	// is always square
	Matrix               *CompressedSparseRowMatrix `protobuf:"bytes,2,opt,name=matrix,proto3" json:"matrix,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Couples) Reset()         { *m = Couples{} }
func (m *Couples) String() string { return proto.CompactTextString(m) }
func (*Couples) ProtoMessage()    {}
func (*Couples) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6}
}
func (m *Couples) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Couples.Unmarshal(m, b)
}
func (m *Couples) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Couples.Marshal(b, m, deterministic)
}
func (m *Couples) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Couples.Merge(m, src)
}
func (m *Couples) XXX_Size() int {
	return xxx_messageInfo_Couples.Size(m)
}
func (m *Couples) XXX_DiscardUnknown() {
	xxx_messageInfo_Couples.DiscardUnknown(m)
}

var xxx_messageInfo_Couples proto.InternalMessageInfo

func (m *Couples) GetIndex() []string {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *Couples) GetMatrix() *CompressedSparseRowMatrix {
	if m != nil {
		return m.Matrix
	}
	return nil
}

type TouchedFiles struct {
	Files                []int32  `protobuf:"varint,1,rep,packed,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TouchedFiles) Reset()         { *m = TouchedFiles{} }
func (m *TouchedFiles) String() string { return proto.CompactTextString(m) }
func (*TouchedFiles) ProtoMessage()    {}
func (*TouchedFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{7}
}
func (m *TouchedFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TouchedFiles.Unmarshal(m, b)
}
func (m *TouchedFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TouchedFiles.Marshal(b, m, deterministic)
}
func (m *TouchedFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TouchedFiles.Merge(m, src)
}
func (m *TouchedFiles) XXX_Size() int {
	return xxx_messageInfo_TouchedFiles.Size(m)
}
func (m *TouchedFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_TouchedFiles.DiscardUnknown(m)
}

var xxx_messageInfo_TouchedFiles proto.InternalMessageInfo

func (m *TouchedFiles) GetFiles() []int32 {
	if m != nil {
		return m.Files
	}
	return nil
}

type CouplesAnalysisResults struct {
	FileCouples   *Couples `protobuf:"bytes,6,opt,name=file_couples,json=fileCouples,proto3" json:"file_couples,omitempty"`
	PeopleCouples *Couples `protobuf:"bytes,7,opt,name=people_couples,json=peopleCouples,proto3" json:"people_couples,omitempty"`
	// order corresponds to `people_couples::index`
	PeopleFiles []*TouchedFiles `protobuf:"bytes,8,rep,name=people_files,json=peopleFiles,proto3" json:"people_files,omitempty"`
	// order corresponds to `file_couples::index`
	FilesLines           []int32  `protobuf:"varint,9,rep,packed,name=files_lines,json=filesLines,proto3" json:"files_lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CouplesAnalysisResults) Reset()         { *m = CouplesAnalysisResults{} }
func (m *CouplesAnalysisResults) String() string { return proto.CompactTextString(m) }
func (*CouplesAnalysisResults) ProtoMessage()    {}
func (*CouplesAnalysisResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{8}
}
func (m *CouplesAnalysisResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CouplesAnalysisResults.Unmarshal(m, b)
}
func (m *CouplesAnalysisResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CouplesAnalysisResults.Marshal(b, m, deterministic)
}
func (m *CouplesAnalysisResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CouplesAnalysisResults.Merge(m, src)
}
func (m *CouplesAnalysisResults) XXX_Size() int {
	return xxx_messageInfo_CouplesAnalysisResults.Size(m)
}
func (m *CouplesAnalysisResults) XXX_DiscardUnknown() {
	xxx_messageInfo_CouplesAnalysisResults.DiscardUnknown(m)
}

var xxx_messageInfo_CouplesAnalysisResults proto.InternalMessageInfo

func (m *CouplesAnalysisResults) GetFileCouples() *Couples {
	if m != nil {
		return m.FileCouples
	}
	return nil
}

func (m *CouplesAnalysisResults) GetPeopleCouples() *Couples {
	if m != nil {
		return m.PeopleCouples
	}
	return nil
}

func (m *CouplesAnalysisResults) GetPeopleFiles() []*TouchedFiles {
	if m != nil {
		return m.PeopleFiles
	}
	return nil
}

func (m *CouplesAnalysisResults) GetFilesLines() []int32 {
	if m != nil {
		return m.FilesLines
	}
	return nil
}

type UASTChange struct {
	FileName             string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	SrcBefore            string   `protobuf:"bytes,2,opt,name=src_before,json=srcBefore,proto3" json:"src_before,omitempty"`
	SrcAfter             string   `protobuf:"bytes,3,opt,name=src_after,json=srcAfter,proto3" json:"src_after,omitempty"`
	UastBefore           string   `protobuf:"bytes,4,opt,name=uast_before,json=uastBefore,proto3" json:"uast_before,omitempty"`
	UastAfter            string   `protobuf:"bytes,5,opt,name=uast_after,json=uastAfter,proto3" json:"uast_after,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UASTChange) Reset()         { *m = UASTChange{} }
func (m *UASTChange) String() string { return proto.CompactTextString(m) }
func (*UASTChange) ProtoMessage()    {}
func (*UASTChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{9}
}
func (m *UASTChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UASTChange.Unmarshal(m, b)
}
func (m *UASTChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UASTChange.Marshal(b, m, deterministic)
}
func (m *UASTChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UASTChange.Merge(m, src)
}
func (m *UASTChange) XXX_Size() int {
	return xxx_messageInfo_UASTChange.Size(m)
}
func (m *UASTChange) XXX_DiscardUnknown() {
	xxx_messageInfo_UASTChange.DiscardUnknown(m)
}

var xxx_messageInfo_UASTChange proto.InternalMessageInfo

func (m *UASTChange) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *UASTChange) GetSrcBefore() string {
	if m != nil {
		return m.SrcBefore
	}
	return ""
}

func (m *UASTChange) GetSrcAfter() string {
	if m != nil {
		return m.SrcAfter
	}
	return ""
}

func (m *UASTChange) GetUastBefore() string {
	if m != nil {
		return m.UastBefore
	}
	return ""
}

func (m *UASTChange) GetUastAfter() string {
	if m != nil {
		return m.UastAfter
	}
	return ""
}

type UASTChangesSaverResults struct {
	Changes              []*UASTChange `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UASTChangesSaverResults) Reset()         { *m = UASTChangesSaverResults{} }
func (m *UASTChangesSaverResults) String() string { return proto.CompactTextString(m) }
func (*UASTChangesSaverResults) ProtoMessage()    {}
func (*UASTChangesSaverResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{10}
}
func (m *UASTChangesSaverResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UASTChangesSaverResults.Unmarshal(m, b)
}
func (m *UASTChangesSaverResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UASTChangesSaverResults.Marshal(b, m, deterministic)
}
func (m *UASTChangesSaverResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UASTChangesSaverResults.Merge(m, src)
}
func (m *UASTChangesSaverResults) XXX_Size() int {
	return xxx_messageInfo_UASTChangesSaverResults.Size(m)
}
func (m *UASTChangesSaverResults) XXX_DiscardUnknown() {
	xxx_messageInfo_UASTChangesSaverResults.DiscardUnknown(m)
}

var xxx_messageInfo_UASTChangesSaverResults proto.InternalMessageInfo

func (m *UASTChangesSaverResults) GetChanges() []*UASTChange {
	if m != nil {
		return m.Changes
	}
	return nil
}

type ShotnessRecord struct {
	Type                 string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	File                 string          `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Counters             map[int32]int32 `protobuf:"bytes,4,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ShotnessRecord) Reset()         { *m = ShotnessRecord{} }
func (m *ShotnessRecord) String() string { return proto.CompactTextString(m) }
func (*ShotnessRecord) ProtoMessage()    {}
func (*ShotnessRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{11}
}
func (m *ShotnessRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShotnessRecord.Unmarshal(m, b)
}
func (m *ShotnessRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShotnessRecord.Marshal(b, m, deterministic)
}
func (m *ShotnessRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShotnessRecord.Merge(m, src)
}
func (m *ShotnessRecord) XXX_Size() int {
	return xxx_messageInfo_ShotnessRecord.Size(m)
}
func (m *ShotnessRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ShotnessRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ShotnessRecord proto.InternalMessageInfo

func (m *ShotnessRecord) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ShotnessRecord) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShotnessRecord) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *ShotnessRecord) GetCounters() map[int32]int32 {
	if m != nil {
		return m.Counters
	}
	return nil
}

type ShotnessAnalysisResults struct {
	Records              []*ShotnessRecord `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShotnessAnalysisResults) Reset()         { *m = ShotnessAnalysisResults{} }
func (m *ShotnessAnalysisResults) String() string { return proto.CompactTextString(m) }
func (*ShotnessAnalysisResults) ProtoMessage()    {}
func (*ShotnessAnalysisResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{12}
}
func (m *ShotnessAnalysisResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShotnessAnalysisResults.Unmarshal(m, b)
}
func (m *ShotnessAnalysisResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShotnessAnalysisResults.Marshal(b, m, deterministic)
}
func (m *ShotnessAnalysisResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShotnessAnalysisResults.Merge(m, src)
}
func (m *ShotnessAnalysisResults) XXX_Size() int {
	return xxx_messageInfo_ShotnessAnalysisResults.Size(m)
}
func (m *ShotnessAnalysisResults) XXX_DiscardUnknown() {
	xxx_messageInfo_ShotnessAnalysisResults.DiscardUnknown(m)
}

var xxx_messageInfo_ShotnessAnalysisResults proto.InternalMessageInfo

func (m *ShotnessAnalysisResults) GetRecords() []*ShotnessRecord {
	if m != nil {
		return m.Records
	}
	return nil
}

type FileHistory struct {
	Commits              []string             `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	ChangesByDeveloper   map[int32]*LineStats `protobuf:"bytes,2,rep,name=changes_by_developer,json=changesByDeveloper,proto3" json:"changes_by_developer,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FileHistory) Reset()         { *m = FileHistory{} }
func (m *FileHistory) String() string { return proto.CompactTextString(m) }
func (*FileHistory) ProtoMessage()    {}
func (*FileHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{13}
}
func (m *FileHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileHistory.Unmarshal(m, b)
}
func (m *FileHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileHistory.Marshal(b, m, deterministic)
}
func (m *FileHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileHistory.Merge(m, src)
}
func (m *FileHistory) XXX_Size() int {
	return xxx_messageInfo_FileHistory.Size(m)
}
func (m *FileHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_FileHistory.DiscardUnknown(m)
}

var xxx_messageInfo_FileHistory proto.InternalMessageInfo

func (m *FileHistory) GetCommits() []string {
	if m != nil {
		return m.Commits
	}
	return nil
}

func (m *FileHistory) GetChangesByDeveloper() map[int32]*LineStats {
	if m != nil {
		return m.ChangesByDeveloper
	}
	return nil
}

type FileHistoryResultMessage struct {
	Files                map[string]*FileHistory `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *FileHistoryResultMessage) Reset()         { *m = FileHistoryResultMessage{} }
func (m *FileHistoryResultMessage) String() string { return proto.CompactTextString(m) }
func (*FileHistoryResultMessage) ProtoMessage()    {}
func (*FileHistoryResultMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{14}
}
func (m *FileHistoryResultMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileHistoryResultMessage.Unmarshal(m, b)
}
func (m *FileHistoryResultMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileHistoryResultMessage.Marshal(b, m, deterministic)
}
func (m *FileHistoryResultMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileHistoryResultMessage.Merge(m, src)
}
func (m *FileHistoryResultMessage) XXX_Size() int {
	return xxx_messageInfo_FileHistoryResultMessage.Size(m)
}
func (m *FileHistoryResultMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FileHistoryResultMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FileHistoryResultMessage proto.InternalMessageInfo

func (m *FileHistoryResultMessage) GetFiles() map[string]*FileHistory {
	if m != nil {
		return m.Files
	}
	return nil
}

type LineStats struct {
	Added                int32    `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	Removed              int32    `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
	Changed              int32    `protobuf:"varint,3,opt,name=changed,proto3" json:"changed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LineStats) Reset()         { *m = LineStats{} }
func (m *LineStats) String() string { return proto.CompactTextString(m) }
func (*LineStats) ProtoMessage()    {}
func (*LineStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{15}
}
func (m *LineStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LineStats.Unmarshal(m, b)
}
func (m *LineStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LineStats.Marshal(b, m, deterministic)
}
func (m *LineStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LineStats.Merge(m, src)
}
func (m *LineStats) XXX_Size() int {
	return xxx_messageInfo_LineStats.Size(m)
}
func (m *LineStats) XXX_DiscardUnknown() {
	xxx_messageInfo_LineStats.DiscardUnknown(m)
}

var xxx_messageInfo_LineStats proto.InternalMessageInfo

func (m *LineStats) GetAdded() int32 {
	if m != nil {
		return m.Added
	}
	return 0
}

func (m *LineStats) GetRemoved() int32 {
	if m != nil {
		return m.Removed
	}
	return 0
}

func (m *LineStats) GetChanged() int32 {
	if m != nil {
		return m.Changed
	}
	return 0
}

type DevTick struct {
	Commits              int32                 `protobuf:"varint,1,opt,name=commits,proto3" json:"commits,omitempty"`
	Stats                *LineStats            `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	Languages            map[string]*LineStats `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DevTick) Reset()         { *m = DevTick{} }
func (m *DevTick) String() string { return proto.CompactTextString(m) }
func (*DevTick) ProtoMessage()    {}
func (*DevTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{16}
}
func (m *DevTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevTick.Unmarshal(m, b)
}
func (m *DevTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevTick.Marshal(b, m, deterministic)
}
func (m *DevTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevTick.Merge(m, src)
}
func (m *DevTick) XXX_Size() int {
	return xxx_messageInfo_DevTick.Size(m)
}
func (m *DevTick) XXX_DiscardUnknown() {
	xxx_messageInfo_DevTick.DiscardUnknown(m)
}

var xxx_messageInfo_DevTick proto.InternalMessageInfo

func (m *DevTick) GetCommits() int32 {
	if m != nil {
		return m.Commits
	}
	return 0
}

func (m *DevTick) GetStats() *LineStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *DevTick) GetLanguages() map[string]*LineStats {
	if m != nil {
		return m.Languages
	}
	return nil
}

type TickDevs struct {
	Devs                 map[int32]*DevTick `protobuf:"bytes,1,rep,name=devs,proto3" json:"devs,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TickDevs) Reset()         { *m = TickDevs{} }
func (m *TickDevs) String() string { return proto.CompactTextString(m) }
func (*TickDevs) ProtoMessage()    {}
func (*TickDevs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{17}
}
func (m *TickDevs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickDevs.Unmarshal(m, b)
}
func (m *TickDevs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickDevs.Marshal(b, m, deterministic)
}
func (m *TickDevs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickDevs.Merge(m, src)
}
func (m *TickDevs) XXX_Size() int {
	return xxx_messageInfo_TickDevs.Size(m)
}
func (m *TickDevs) XXX_DiscardUnknown() {
	xxx_messageInfo_TickDevs.DiscardUnknown(m)
}

var xxx_messageInfo_TickDevs proto.InternalMessageInfo

func (m *TickDevs) GetDevs() map[int32]*DevTick {
	if m != nil {
		return m.Devs
	}
	return nil
}

type DevsAnalysisResults struct {
	Ticks map[int32]*TickDevs `protobuf:"bytes,1,rep,name=ticks,proto3" json:"ticks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// developer identities, the indexes correspond to TickDevs' keys.
	DevIndex []string `protobuf:"bytes,2,rep,name=dev_index,json=devIndex,proto3" json:"dev_index,omitempty"`
	// how long each tick is, as an int64 nanosecond count (Go's time.Duration)
	TickSize             int64    `protobuf:"varint,8,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevsAnalysisResults) Reset()         { *m = DevsAnalysisResults{} }
func (m *DevsAnalysisResults) String() string { return proto.CompactTextString(m) }
func (*DevsAnalysisResults) ProtoMessage()    {}
func (*DevsAnalysisResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{18}
}
func (m *DevsAnalysisResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevsAnalysisResults.Unmarshal(m, b)
}
func (m *DevsAnalysisResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevsAnalysisResults.Marshal(b, m, deterministic)
}
func (m *DevsAnalysisResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevsAnalysisResults.Merge(m, src)
}
func (m *DevsAnalysisResults) XXX_Size() int {
	return xxx_messageInfo_DevsAnalysisResults.Size(m)
}
func (m *DevsAnalysisResults) XXX_DiscardUnknown() {
	xxx_messageInfo_DevsAnalysisResults.DiscardUnknown(m)
}

var xxx_messageInfo_DevsAnalysisResults proto.InternalMessageInfo

func (m *DevsAnalysisResults) GetTicks() map[int32]*TickDevs {
	if m != nil {
		return m.Ticks
	}
	return nil
}

func (m *DevsAnalysisResults) GetDevIndex() []string {
	if m != nil {
		return m.DevIndex
	}
	return nil
}

func (m *DevsAnalysisResults) GetTickSize() int64 {
	if m != nil {
		return m.TickSize
	}
	return 0
}

type Sentiment struct {
	Value                float32  `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Comments             []string `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
	Commits              []string `protobuf:"bytes,3,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sentiment) Reset()         { *m = Sentiment{} }
func (m *Sentiment) String() string { return proto.CompactTextString(m) }
func (*Sentiment) ProtoMessage()    {}
func (*Sentiment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{19}
}
func (m *Sentiment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sentiment.Unmarshal(m, b)
}
func (m *Sentiment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sentiment.Marshal(b, m, deterministic)
}
func (m *Sentiment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sentiment.Merge(m, src)
}
func (m *Sentiment) XXX_Size() int {
	return xxx_messageInfo_Sentiment.Size(m)
}
func (m *Sentiment) XXX_DiscardUnknown() {
	xxx_messageInfo_Sentiment.DiscardUnknown(m)
}

var xxx_messageInfo_Sentiment proto.InternalMessageInfo

func (m *Sentiment) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Sentiment) GetComments() []string {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *Sentiment) GetCommits() []string {
	if m != nil {
		return m.Commits
	}
	return nil
}

type CommentSentimentResults struct {
	SentimentByTick      map[int32]*Sentiment `protobuf:"bytes,1,rep,name=sentiment_by_tick,json=sentimentByTick,proto3" json:"sentiment_by_tick,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CommentSentimentResults) Reset()         { *m = CommentSentimentResults{} }
func (m *CommentSentimentResults) String() string { return proto.CompactTextString(m) }
func (*CommentSentimentResults) ProtoMessage()    {}
func (*CommentSentimentResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{20}
}
func (m *CommentSentimentResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentSentimentResults.Unmarshal(m, b)
}
func (m *CommentSentimentResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentSentimentResults.Marshal(b, m, deterministic)
}
func (m *CommentSentimentResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentSentimentResults.Merge(m, src)
}
func (m *CommentSentimentResults) XXX_Size() int {
	return xxx_messageInfo_CommentSentimentResults.Size(m)
}
func (m *CommentSentimentResults) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentSentimentResults.DiscardUnknown(m)
}

var xxx_messageInfo_CommentSentimentResults proto.InternalMessageInfo

func (m *CommentSentimentResults) GetSentimentByTick() map[int32]*Sentiment {
	if m != nil {
		return m.SentimentByTick
	}
	return nil
}

type CommitFile struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Language             string     `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Stats                *LineStats `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommitFile) Reset()         { *m = CommitFile{} }
func (m *CommitFile) String() string { return proto.CompactTextString(m) }
func (*CommitFile) ProtoMessage()    {}
func (*CommitFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{21}
}
func (m *CommitFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitFile.Unmarshal(m, b)
}
func (m *CommitFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitFile.Marshal(b, m, deterministic)
}
func (m *CommitFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitFile.Merge(m, src)
}
func (m *CommitFile) XXX_Size() int {
	return xxx_messageInfo_CommitFile.Size(m)
}
func (m *CommitFile) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitFile.DiscardUnknown(m)
}

var xxx_messageInfo_CommitFile proto.InternalMessageInfo

func (m *CommitFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CommitFile) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *CommitFile) GetStats() *LineStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Commit struct {
	Hash                 string        `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	WhenUnixTime         int64         `protobuf:"varint,2,opt,name=when_unix_time,json=whenUnixTime,proto3" json:"when_unix_time,omitempty"`
	Author               int32         `protobuf:"varint,3,opt,name=author,proto3" json:"author,omitempty"`
	Files                []*CommitFile `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{22}
}
func (m *Commit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commit.Unmarshal(m, b)
}
func (m *Commit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commit.Marshal(b, m, deterministic)
}
func (m *Commit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commit.Merge(m, src)
}
func (m *Commit) XXX_Size() int {
	return xxx_messageInfo_Commit.Size(m)
}
func (m *Commit) XXX_DiscardUnknown() {
	xxx_messageInfo_Commit.DiscardUnknown(m)
}

var xxx_messageInfo_Commit proto.InternalMessageInfo

func (m *Commit) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Commit) GetWhenUnixTime() int64 {
	if m != nil {
		return m.WhenUnixTime
	}
	return 0
}

func (m *Commit) GetAuthor() int32 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *Commit) GetFiles() []*CommitFile {
	if m != nil {
		return m.Files
	}
	return nil
}

type CommitsAnalysisResults struct {
	Commits              []*Commit `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	AuthorIndex          []string  `protobuf:"bytes,2,rep,name=author_index,json=authorIndex,proto3" json:"author_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommitsAnalysisResults) Reset()         { *m = CommitsAnalysisResults{} }
func (m *CommitsAnalysisResults) String() string { return proto.CompactTextString(m) }
func (*CommitsAnalysisResults) ProtoMessage()    {}
func (*CommitsAnalysisResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{23}
}
func (m *CommitsAnalysisResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitsAnalysisResults.Unmarshal(m, b)
}
func (m *CommitsAnalysisResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitsAnalysisResults.Marshal(b, m, deterministic)
}
func (m *CommitsAnalysisResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitsAnalysisResults.Merge(m, src)
}
func (m *CommitsAnalysisResults) XXX_Size() int {
	return xxx_messageInfo_CommitsAnalysisResults.Size(m)
}
func (m *CommitsAnalysisResults) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitsAnalysisResults.DiscardUnknown(m)
}

var xxx_messageInfo_CommitsAnalysisResults proto.InternalMessageInfo

func (m *CommitsAnalysisResults) GetCommits() []*Commit {
	if m != nil {
		return m.Commits
	}
	return nil
}

func (m *CommitsAnalysisResults) GetAuthorIndex() []string {
	if m != nil {
		return m.AuthorIndex
	}
	return nil
}

type Typo struct {
	Wrong                string   `protobuf:"bytes,1,opt,name=wrong,proto3" json:"wrong,omitempty"`
	Correct              string   `protobuf:"bytes,2,opt,name=correct,proto3" json:"correct,omitempty"`
	Commit               string   `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	File                 string   `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Line                 int32    `protobuf:"varint,5,opt,name=line,proto3" json:"line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Typo) Reset()         { *m = Typo{} }
func (m *Typo) String() string { return proto.CompactTextString(m) }
func (*Typo) ProtoMessage()    {}
func (*Typo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{24}
}
func (m *Typo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Typo.Unmarshal(m, b)
}
func (m *Typo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Typo.Marshal(b, m, deterministic)
}
func (m *Typo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Typo.Merge(m, src)
}
func (m *Typo) XXX_Size() int {
	return xxx_messageInfo_Typo.Size(m)
}
func (m *Typo) XXX_DiscardUnknown() {
	xxx_messageInfo_Typo.DiscardUnknown(m)
}

var xxx_messageInfo_Typo proto.InternalMessageInfo

func (m *Typo) GetWrong() string {
	if m != nil {
		return m.Wrong
	}
	return ""
}

func (m *Typo) GetCorrect() string {
	if m != nil {
		return m.Correct
	}
	return ""
}

func (m *Typo) GetCommit() string {
	if m != nil {
		return m.Commit
	}
	return ""
}

func (m *Typo) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Typo) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

type TyposDataset struct {
	Typos                []*Typo  `protobuf:"bytes,1,rep,name=typos,proto3" json:"typos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TyposDataset) Reset()         { *m = TyposDataset{} }
func (m *TyposDataset) String() string { return proto.CompactTextString(m) }
func (*TyposDataset) ProtoMessage()    {}
func (*TyposDataset) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{25}
}
func (m *TyposDataset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TyposDataset.Unmarshal(m, b)
}
func (m *TyposDataset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TyposDataset.Marshal(b, m, deterministic)
}
func (m *TyposDataset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TyposDataset.Merge(m, src)
}
func (m *TyposDataset) XXX_Size() int {
	return xxx_messageInfo_TyposDataset.Size(m)
}
func (m *TyposDataset) XXX_DiscardUnknown() {
	xxx_messageInfo_TyposDataset.DiscardUnknown(m)
}

var xxx_messageInfo_TyposDataset proto.InternalMessageInfo

func (m *TyposDataset) GetTypos() []*Typo {
	if m != nil {
		return m.Typos
	}
	return nil
}

type ImportsPerTick struct {
	Counts               map[int32]int64 `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ImportsPerTick) Reset()         { *m = ImportsPerTick{} }
func (m *ImportsPerTick) String() string { return proto.CompactTextString(m) }
func (*ImportsPerTick) ProtoMessage()    {}
func (*ImportsPerTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{26}
}
func (m *ImportsPerTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportsPerTick.Unmarshal(m, b)
}
func (m *ImportsPerTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportsPerTick.Marshal(b, m, deterministic)
}
func (m *ImportsPerTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportsPerTick.Merge(m, src)
}
func (m *ImportsPerTick) XXX_Size() int {
	return xxx_messageInfo_ImportsPerTick.Size(m)
}
func (m *ImportsPerTick) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportsPerTick.DiscardUnknown(m)
}

var xxx_messageInfo_ImportsPerTick proto.InternalMessageInfo

func (m *ImportsPerTick) GetCounts() map[int32]int64 {
	if m != nil {
		return m.Counts
	}
	return nil
}

type ImportsPerLanguage struct {
	Ticks                map[string]*ImportsPerTick `protobuf:"bytes,1,rep,name=ticks,proto3" json:"ticks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ImportsPerLanguage) Reset()         { *m = ImportsPerLanguage{} }
func (m *ImportsPerLanguage) String() string { return proto.CompactTextString(m) }
func (*ImportsPerLanguage) ProtoMessage()    {}
func (*ImportsPerLanguage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{27}
}
func (m *ImportsPerLanguage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportsPerLanguage.Unmarshal(m, b)
}
func (m *ImportsPerLanguage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportsPerLanguage.Marshal(b, m, deterministic)
}
func (m *ImportsPerLanguage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportsPerLanguage.Merge(m, src)
}
func (m *ImportsPerLanguage) XXX_Size() int {
	return xxx_messageInfo_ImportsPerLanguage.Size(m)
}
func (m *ImportsPerLanguage) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportsPerLanguage.DiscardUnknown(m)
}

var xxx_messageInfo_ImportsPerLanguage proto.InternalMessageInfo

func (m *ImportsPerLanguage) GetTicks() map[string]*ImportsPerTick {
	if m != nil {
		return m.Ticks
	}
	return nil
}

type ImportsPerDeveloper struct {
	Languages            map[string]*ImportsPerLanguage `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *ImportsPerDeveloper) Reset()         { *m = ImportsPerDeveloper{} }
func (m *ImportsPerDeveloper) String() string { return proto.CompactTextString(m) }
func (*ImportsPerDeveloper) ProtoMessage()    {}
func (*ImportsPerDeveloper) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{28}
}
func (m *ImportsPerDeveloper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportsPerDeveloper.Unmarshal(m, b)
}
func (m *ImportsPerDeveloper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportsPerDeveloper.Marshal(b, m, deterministic)
}
func (m *ImportsPerDeveloper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportsPerDeveloper.Merge(m, src)
}
func (m *ImportsPerDeveloper) XXX_Size() int {
	return xxx_messageInfo_ImportsPerDeveloper.Size(m)
}
func (m *ImportsPerDeveloper) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportsPerDeveloper.DiscardUnknown(m)
}

var xxx_messageInfo_ImportsPerDeveloper proto.InternalMessageInfo

func (m *ImportsPerDeveloper) GetLanguages() map[string]*ImportsPerLanguage {
	if m != nil {
		return m.Languages
	}
	return nil
}

type ImportsPerDeveloperResults struct {
	Imports     []*ImportsPerDeveloper `protobuf:"bytes,1,rep,name=imports,proto3" json:"imports,omitempty"`
	AuthorIndex []string               `protobuf:"bytes,2,rep,name=author_index,json=authorIndex,proto3" json:"author_index,omitempty"`
	// how long each tick is, as an int64 nanosecond count (Go's time.Duration)
	TickSize             int64    `protobuf:"varint,3,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportsPerDeveloperResults) Reset()         { *m = ImportsPerDeveloperResults{} }
func (m *ImportsPerDeveloperResults) String() string { return proto.CompactTextString(m) }
func (*ImportsPerDeveloperResults) ProtoMessage()    {}
func (*ImportsPerDeveloperResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{29}
}
func (m *ImportsPerDeveloperResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportsPerDeveloperResults.Unmarshal(m, b)
}
func (m *ImportsPerDeveloperResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportsPerDeveloperResults.Marshal(b, m, deterministic)
}
func (m *ImportsPerDeveloperResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportsPerDeveloperResults.Merge(m, src)
}
func (m *ImportsPerDeveloperResults) XXX_Size() int {
	return xxx_messageInfo_ImportsPerDeveloperResults.Size(m)
}
func (m *ImportsPerDeveloperResults) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportsPerDeveloperResults.DiscardUnknown(m)
}

var xxx_messageInfo_ImportsPerDeveloperResults proto.InternalMessageInfo

func (m *ImportsPerDeveloperResults) GetImports() []*ImportsPerDeveloper {
	if m != nil {
		return m.Imports
	}
	return nil
}

func (m *ImportsPerDeveloperResults) GetAuthorIndex() []string {
	if m != nil {
		return m.AuthorIndex
	}
	return nil
}

func (m *ImportsPerDeveloperResults) GetTickSize() int64 {
	if m != nil {
		return m.TickSize
	}
	return 0
}

type DeveloperTemporalActivity struct {
	// Sunday=0 to Saturday=6 (length 7)
	Weekdays []int32 `protobuf:"varint,1,rep,packed,name=weekdays,proto3" json:"weekdays,omitempty"`
	// 0-23 (length 24)
	Hours []int32 `protobuf:"varint,2,rep,packed,name=hours,proto3" json:"hours,omitempty"`
	// January=0 to December=11 (length 12)
	Months []int32 `protobuf:"varint,3,rep,packed,name=months,proto3" json:"months,omitempty"`
	// ISO week 1-53 stored at indices 0-52 (length 53)
	Weeks                []int32  `protobuf:"varint,4,rep,packed,name=weeks,proto3" json:"weeks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeveloperTemporalActivity) Reset()         { *m = DeveloperTemporalActivity{} }
func (m *DeveloperTemporalActivity) String() string { return proto.CompactTextString(m) }
func (*DeveloperTemporalActivity) ProtoMessage()    {}
func (*DeveloperTemporalActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{30}
}
func (m *DeveloperTemporalActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeveloperTemporalActivity.Unmarshal(m, b)
}
func (m *DeveloperTemporalActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeveloperTemporalActivity.Marshal(b, m, deterministic)
}
func (m *DeveloperTemporalActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeveloperTemporalActivity.Merge(m, src)
}
func (m *DeveloperTemporalActivity) XXX_Size() int {
	return xxx_messageInfo_DeveloperTemporalActivity.Size(m)
}
func (m *DeveloperTemporalActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_DeveloperTemporalActivity.DiscardUnknown(m)
}

var xxx_messageInfo_DeveloperTemporalActivity proto.InternalMessageInfo

func (m *DeveloperTemporalActivity) GetWeekdays() []int32 {
	if m != nil {
		return m.Weekdays
	}
	return nil
}

func (m *DeveloperTemporalActivity) GetHours() []int32 {
	if m != nil {
		return m.Hours
	}
	return nil
}

func (m *DeveloperTemporalActivity) GetMonths() []int32 {
	if m != nil {
		return m.Months
	}
	return nil
}

func (m *DeveloperTemporalActivity) GetWeeks() []int32 {
	if m != nil {
		return m.Weeks
	}
	return nil
}

type TemporalActivityResults struct {
	// developer index -> temporal activity
	Activities map[int32]*DeveloperTemporalActivity `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// developer identities, the indexes correspond to activities' keys
	DevIndex []string `protobuf:"bytes,2,rep,name=dev_index,json=devIndex,proto3" json:"dev_index,omitempty"`
	// "commits" or "lines"
	Mode                 string   `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemporalActivityResults) Reset()         { *m = TemporalActivityResults{} }
func (m *TemporalActivityResults) String() string { return proto.CompactTextString(m) }
func (*TemporalActivityResults) ProtoMessage()    {}
func (*TemporalActivityResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{31}
}
func (m *TemporalActivityResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemporalActivityResults.Unmarshal(m, b)
}
func (m *TemporalActivityResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemporalActivityResults.Marshal(b, m, deterministic)
}
func (m *TemporalActivityResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemporalActivityResults.Merge(m, src)
}
func (m *TemporalActivityResults) XXX_Size() int {
	return xxx_messageInfo_TemporalActivityResults.Size(m)
}
func (m *TemporalActivityResults) XXX_DiscardUnknown() {
	xxx_messageInfo_TemporalActivityResults.DiscardUnknown(m)
}

var xxx_messageInfo_TemporalActivityResults proto.InternalMessageInfo

func (m *TemporalActivityResults) GetActivities() map[int32]*DeveloperTemporalActivity {
	if m != nil {
		return m.Activities
	}
	return nil
}

func (m *TemporalActivityResults) GetDevIndex() []string {
	if m != nil {
		return m.DevIndex
	}
	return nil
}

func (m *TemporalActivityResults) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type AnalysisResults struct {
	Header *Metadata `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// the mapped values are dynamic messages which require the second parsing pass.
	Contents             map[string][]byte `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AnalysisResults) Reset()         { *m = AnalysisResults{} }
func (m *AnalysisResults) String() string { return proto.CompactTextString(m) }
func (*AnalysisResults) ProtoMessage()    {}
func (*AnalysisResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{32}
}
func (m *AnalysisResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalysisResults.Unmarshal(m, b)
}
func (m *AnalysisResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalysisResults.Marshal(b, m, deterministic)
}
func (m *AnalysisResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalysisResults.Merge(m, src)
}
func (m *AnalysisResults) XXX_Size() int {
	return xxx_messageInfo_AnalysisResults.Size(m)
}
func (m *AnalysisResults) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalysisResults.DiscardUnknown(m)
}

var xxx_messageInfo_AnalysisResults proto.InternalMessageInfo

func (m *AnalysisResults) GetHeader() *Metadata {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AnalysisResults) GetContents() map[string][]byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "Metadata")
	proto.RegisterMapType((map[string]float64)(nil), "Metadata.RunTimePerItemEntry")
	proto.RegisterType((*BurndownSparseMatrixRow)(nil), "BurndownSparseMatrixRow")
	proto.RegisterType((*BurndownSparseMatrix)(nil), "BurndownSparseMatrix")
	proto.RegisterType((*FilesOwnership)(nil), "FilesOwnership")
	proto.RegisterMapType((map[int32]int32)(nil), "FilesOwnership.ValueEntry")
	proto.RegisterType((*BurndownAnalysisResults)(nil), "BurndownAnalysisResults")
	proto.RegisterType((*CompressedSparseRowMatrix)(nil), "CompressedSparseRowMatrix")
	proto.RegisterType((*Couples)(nil), "Couples")
	proto.RegisterType((*TouchedFiles)(nil), "TouchedFiles")
	proto.RegisterType((*CouplesAnalysisResults)(nil), "CouplesAnalysisResults")
	proto.RegisterType((*UASTChange)(nil), "UASTChange")
	proto.RegisterType((*UASTChangesSaverResults)(nil), "UASTChangesSaverResults")
	proto.RegisterType((*ShotnessRecord)(nil), "ShotnessRecord")
	proto.RegisterMapType((map[int32]int32)(nil), "ShotnessRecord.CountersEntry")
	proto.RegisterType((*ShotnessAnalysisResults)(nil), "ShotnessAnalysisResults")
	proto.RegisterType((*FileHistory)(nil), "FileHistory")
	proto.RegisterMapType((map[int32]*LineStats)(nil), "FileHistory.ChangesByDeveloperEntry")
	proto.RegisterType((*FileHistoryResultMessage)(nil), "FileHistoryResultMessage")
	proto.RegisterMapType((map[string]*FileHistory)(nil), "FileHistoryResultMessage.FilesEntry")
	proto.RegisterType((*LineStats)(nil), "LineStats")
	proto.RegisterType((*DevTick)(nil), "DevTick")
	proto.RegisterMapType((map[string]*LineStats)(nil), "DevTick.LanguagesEntry")
	proto.RegisterType((*TickDevs)(nil), "TickDevs")
	proto.RegisterMapType((map[int32]*DevTick)(nil), "TickDevs.DevsEntry")
	proto.RegisterType((*DevsAnalysisResults)(nil), "DevsAnalysisResults")
	proto.RegisterMapType((map[int32]*TickDevs)(nil), "DevsAnalysisResults.TicksEntry")
	proto.RegisterType((*Sentiment)(nil), "Sentiment")
	proto.RegisterType((*CommentSentimentResults)(nil), "CommentSentimentResults")
	proto.RegisterMapType((map[int32]*Sentiment)(nil), "CommentSentimentResults.SentimentByTickEntry")
	proto.RegisterType((*CommitFile)(nil), "CommitFile")
	proto.RegisterType((*Commit)(nil), "Commit")
	proto.RegisterType((*CommitsAnalysisResults)(nil), "CommitsAnalysisResults")
	proto.RegisterType((*Typo)(nil), "Typo")
	proto.RegisterType((*TyposDataset)(nil), "TyposDataset")
	proto.RegisterType((*ImportsPerTick)(nil), "ImportsPerTick")
	proto.RegisterMapType((map[int32]int64)(nil), "ImportsPerTick.CountsEntry")
	proto.RegisterType((*ImportsPerLanguage)(nil), "ImportsPerLanguage")
	proto.RegisterMapType((map[string]*ImportsPerTick)(nil), "ImportsPerLanguage.TicksEntry")
	proto.RegisterType((*ImportsPerDeveloper)(nil), "ImportsPerDeveloper")
	proto.RegisterMapType((map[string]*ImportsPerLanguage)(nil), "ImportsPerDeveloper.LanguagesEntry")
	proto.RegisterType((*ImportsPerDeveloperResults)(nil), "ImportsPerDeveloperResults")
	proto.RegisterType((*DeveloperTemporalActivity)(nil), "DeveloperTemporalActivity")
	proto.RegisterType((*TemporalActivityResults)(nil), "TemporalActivityResults")
	proto.RegisterMapType((map[int32]*DeveloperTemporalActivity)(nil), "TemporalActivityResults.ActivitiesEntry")
	proto.RegisterType((*AnalysisResults)(nil), "AnalysisResults")
	proto.RegisterMapType((map[string][]byte)(nil), "AnalysisResults.ContentsEntry")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 1858 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xcd, 0x8f, 0x1b, 0x49,
	0x15, 0x57, 0xdb, 0x6e, 0x7f, 0x3c, 0x7b, 0x6c, 0x52, 0x33, 0x64, 0x9c, 0x8e, 0x92, 0x38, 0x4d,
	0x16, 0x66, 0x09, 0xdb, 0x1b, 0x4d, 0x58, 0x29, 0x1b, 0x2e, 0x4c, 0x66, 0x58, 0x65, 0xa4, 0xcd,
	0x7e, 0xb4, 0x27, 0x8b, 0xf6, 0xb2, 0x56, 0x8f, 0xbb, 0x66, 0xdc, 0x8c, 0x5d, 0xdd, 0xaa, 0xaa,
	0xb6, 0xe3, 0x05, 0x24, 0x4e, 0x9c, 0xb8, 0x72, 0xe5, 0xc6, 0x05, 0xc4, 0x89, 0x7f, 0x01, 0x21,
	0x21, 0x6e, 0xfc, 0x11, 0x5c, 0xf9, 0x17, 0x50, 0x7d, 0xf5, 0x87, 0xd3, 0x9e, 0xcc, 0xde, 0xfa,
	0xbd, 0xf7, 0x7b, 0x55, 0xef, 0xab, 0xde, 0xab, 0x6a, 0x68, 0x27, 0xe7, 0x5e, 0x42, 0x63, 0x1e,
	0xbb, 0xff, 0xad, 0x41, 0xfb, 0x15, 0xe6, 0x41, 0x18, 0xf0, 0x00, 0x0d, 0xa1, 0xb5, 0xc4, 0x94,
	0x45, 0x31, 0x19, 0x5a, 0x23, 0xeb, 0xc0, 0xf6, 0x0d, 0x89, 0x10, 0x34, 0x66, 0x01, 0x9b, 0x0d,
	0x6b, 0x23, 0xeb, 0xa0, 0xe3, 0xcb, 0x6f, 0x74, 0x1f, 0x80, 0xe2, 0x24, 0x66, 0x11, 0x8f, 0xe9,
	0x7a, 0x58, 0x97, 0x92, 0x02, 0x07, 0xfd, 0x10, 0x06, 0xe7, 0xf8, 0x32, 0x22, 0x93, 0x94, 0x44,
	0x6f, 0x26, 0x3c, 0x5a, 0xe0, 0x61, 0x63, 0x64, 0x1d, 0xd4, 0xfd, 0x1d, 0xc9, 0x7e, 0x4d, 0xa2,
	0x37, 0x67, 0xd1, 0x02, 0x23, 0x17, 0x76, 0x30, 0x09, 0x0b, 0x28, 0x5b, 0xa2, 0xba, 0x98, 0x84,
	0x19, 0x66, 0x08, 0xad, 0x69, 0xbc, 0x58, 0x44, 0x9c, 0x0d, 0x9b, 0xca, 0x32, 0x4d, 0xa2, 0x3b,
	0xd0, 0xa6, 0x29, 0x51, 0x8a, 0x2d, 0xa9, 0xd8, 0xa2, 0x29, 0x91, 0x4a, 0x2f, 0xe1, 0x96, 0x11,
	0x4d, 0x12, 0x4c, 0x27, 0x11, 0xc7, 0x8b, 0x61, 0x7b, 0x54, 0x3f, 0xe8, 0x1e, 0xde, 0xf3, 0x8c,
	0xd3, 0x9e, 0xaf, 0xd0, 0x5f, 0x60, 0x7a, 0xca, 0xf1, 0xe2, 0x17, 0x84, 0xd3, 0xb5, 0xdf, 0xa7,
	0x25, 0xa6, 0x73, 0x04, 0xbb, 0x15, 0x30, 0xf4, 0x3d, 0xa8, 0x5f, 0xe1, 0xb5, 0x8c, 0x55, 0xc7,
	0x17, 0x9f, 0x68, 0x0f, 0xec, 0x65, 0x30, 0x4f, 0xb1, 0x0c, 0x94, 0xe5, 0x2b, 0xe2, 0x79, 0xed,
	0x99, 0xe5, 0x3e, 0x85, 0xfd, 0x17, 0x29, 0x25, 0x61, 0xbc, 0x22, 0xe3, 0x24, 0xa0, 0x0c, 0xbf,
	0x0a, 0x38, 0x8d, 0xde, 0xf8, 0xf1, 0x4a, 0x39, 0x37, 0x4f, 0x17, 0x84, 0x0d, 0xad, 0x51, 0xfd,
	0x60, 0xc7, 0x37, 0xa4, 0xfb, 0x17, 0x0b, 0xf6, 0xaa, 0xb4, 0x44, 0x3e, 0x48, 0xb0, 0xc0, 0x7a,
	0x6b, 0xf9, 0x8d, 0x1e, 0x41, 0x9f, 0xa4, 0x8b, 0x73, 0x4c, 0x27, 0xf1, 0xc5, 0x84, 0xc6, 0x2b,
	0x26, 0x8d, 0xb0, 0xfd, 0x9e, 0xe2, 0x7e, 0x7e, 0xe1, 0xc7, 0x2b, 0x86, 0x7e, 0x0c, 0xb7, 0x72,
	0x94, 0xd9, 0xb6, 0x2e, 0x81, 0x03, 0x03, 0x3c, 0x56, 0x6c, 0xf4, 0x13, 0x68, 0xc8, 0x75, 0x1a,
	0x32, 0x66, 0x43, 0x6f, 0x8b, 0x03, 0xbe, 0x44, 0xb9, 0xbf, 0x81, 0xfe, 0x27, 0xd1, 0x1c, 0xb3,
	0xcf, 0x57, 0x04, 0x53, 0x36, 0x8b, 0x12, 0xf4, 0xc4, 0x44, 0xc3, 0x92, 0x0b, 0x38, 0x5e, 0x59,
	0xee, 0x7d, 0x25, 0x84, 0x2a, 0xe2, 0x0a, 0xe8, 0x3c, 0x03, 0xc8, 0x99, 0xc5, 0xf8, 0xda, 0x15,
	0xf1, 0xb5, 0x8b, 0xf1, 0xfd, 0x7d, 0x3d, 0x0f, 0xf0, 0x11, 0x09, 0xe6, 0x6b, 0x16, 0x31, 0x1f,
	0xb3, 0x74, 0xce, 0x19, 0x1a, 0x41, 0xf7, 0x92, 0x06, 0x24, 0x9d, 0x07, 0x34, 0xe2, 0x66, 0xbd,
	0x22, 0x0b, 0x39, 0xd0, 0x66, 0xc1, 0x22, 0x99, 0x47, 0xe4, 0x52, 0x2f, 0x9d, 0xd1, 0xe8, 0x43,
	0x68, 0x25, 0x34, 0xfe, 0x15, 0x9e, 0x72, 0x19, 0xa7, 0xee, 0xe1, 0xf7, 0xab, 0x03, 0x61, 0x50,
	0xe8, 0x31, 0xd8, 0x17, 0xc2, 0x51, 0x1d, 0xb7, 0x2d, 0x70, 0x85, 0x41, 0x1f, 0x40, 0x33, 0xc1,
	0x71, 0x32, 0x17, 0x65, 0x7f, 0x0d, 0x5a, 0x83, 0xd0, 0x29, 0x20, 0xf5, 0x35, 0x89, 0x08, 0xc7,
	0x34, 0x98, 0x72, 0x71, 0x5a, 0x9b, 0xd2, 0x2e, 0xc7, 0x3b, 0x8e, 0x17, 0x09, 0xc5, 0x8c, 0xe1,
	0x50, 0x29, 0xfb, 0xf1, 0x4a, 0xeb, 0xdf, 0x52, 0x5a, 0xa7, 0xb9, 0x12, 0x7a, 0x06, 0x03, 0x69,
	0xc2, 0x24, 0x36, 0x09, 0x19, 0xb6, 0xa4, 0x09, 0x83, 0x8d, 0x3c, 0xf9, 0xfd, 0x8b, 0x72, 0x5e,
	0xef, 0x42, 0x87, 0x47, 0xd3, 0xab, 0x09, 0x8b, 0xbe, 0xc5, 0xc3, 0xb6, 0x3c, 0x74, 0x6d, 0xc1,
	0x18, 0x47, 0xdf, 0x62, 0xf7, 0xef, 0x16, 0xdc, 0xd9, 0x6a, 0x47, 0x45, 0x91, 0x5a, 0x37, 0x2d,
	0xd2, 0x5a, 0x75, 0x91, 0x22, 0x68, 0x88, 0x73, 0x3c, 0xac, 0x8f, 0xea, 0x07, 0x75, 0xbf, 0x61,
	0x1a, 0x59, 0x44, 0xc2, 0x68, 0xaa, 0x73, 0x60, 0xfb, 0x86, 0x44, 0xb7, 0xa1, 0x19, 0x91, 0x30,
	0xe1, 0x54, 0x86, 0xbb, 0xee, 0x6b, 0xca, 0x1d, 0x43, 0xeb, 0x38, 0x4e, 0x13, 0x91, 0x91, 0x3d,
	0xb0, 0x23, 0x12, 0xe2, 0x37, 0xb2, 0x6a, 0x3b, 0xbe, 0x22, 0xd0, 0x21, 0x34, 0x17, 0xd2, 0x05,
	0x69, 0xc7, 0xf5, 0xc1, 0xd6, 0x48, 0xf7, 0x11, 0xf4, 0xce, 0xe2, 0x74, 0x3a, 0xc3, 0xa1, 0x0c,
	0xa8, 0x58, 0x59, 0x15, 0x86, 0x25, 0x8d, 0x52, 0x84, 0xfb, 0x2f, 0x0b, 0x6e, 0xeb, 0xbd, 0x37,
	0x0b, 0xf7, 0x31, 0xf4, 0x04, 0x66, 0x32, 0x55, 0x62, 0x9d, 0xe7, 0xb6, 0xa7, 0xe1, 0x7e, 0x57,
	0x48, 0x8d, 0xdd, 0x1f, 0x42, 0x5f, 0x97, 0x86, 0x81, 0xb7, 0x36, 0xe0, 0x3b, 0x4a, 0x6e, 0x14,
	0x9e, 0x40, 0x4f, 0x2b, 0x28, 0xab, 0x54, 0x6b, 0xdc, 0xf1, 0x8a, 0x36, 0xfb, 0x5d, 0x05, 0x51,
	0x0e, 0x3c, 0x80, 0xae, 0x2a, 0x99, 0x79, 0x44, 0x30, 0x1b, 0x76, 0xa4, 0x1b, 0x20, 0x59, 0x9f,
	0x0a, 0x8e, 0xfb, 0x67, 0x0b, 0xe0, 0xf5, 0xd1, 0xf8, 0xec, 0x78, 0x16, 0x90, 0x4b, 0x2c, 0x0a,
	0x45, 0xda, 0x5f, 0xe8, 0x55, 0x6d, 0xc1, 0xf8, 0x4c, 0xf4, 0xab, 0x7b, 0x00, 0x8c, 0x4e, 0x27,
	0xe7, 0xf8, 0x22, 0xa6, 0x58, 0x4f, 0x96, 0x0e, 0xa3, 0xd3, 0x17, 0x92, 0x21, 0x74, 0x85, 0x38,
	0xb8, 0xe0, 0x98, 0xea, 0xe9, 0xd2, 0x66, 0x74, 0x7a, 0x24, 0x68, 0x61, 0x48, 0x1a, 0x30, 0x6e,
	0x94, 0x1b, 0x6a, 0xf8, 0x08, 0x96, 0xd6, 0xbe, 0x07, 0x92, 0xd2, 0xea, 0xb6, 0x5a, 0x5c, 0x70,
	0xa4, 0xbe, 0xfb, 0x73, 0xd8, 0xcf, 0xcd, 0x64, 0xe3, 0x60, 0x89, 0xa9, 0x89, 0xf9, 0x7b, 0xd0,
	0x9a, 0x2a, 0xb6, 0x6e, 0x5b, 0x5d, 0x2f, 0x87, 0xfa, 0x46, 0xe6, 0xfe, 0xc3, 0x82, 0xfe, 0x78,
	0x16, 0x73, 0x82, 0x19, 0xf3, 0xf1, 0x34, 0xa6, 0xa1, 0xa8, 0x44, 0xbe, 0x4e, 0xb2, 0xa6, 0x2c,
	0xbe, 0xb3, 0x46, 0x5d, 0x2b, 0x34, 0x6a, 0x04, 0x0d, 0x11, 0x04, 0xed, 0x94, 0xfc, 0x46, 0x1f,
	0x43, 0x7b, 0x1a, 0xa7, 0xe2, 0x74, 0x9a, 0xb6, 0x71, 0xcf, 0x2b, 0x2f, 0x2f, 0xb2, 0x28, 0xe5,
	0xaa, 0x61, 0x66, 0x70, 0xe7, 0x67, 0xb0, 0x53, 0x12, 0x7d, 0xa7, 0xb6, 0x79, 0x02, 0xfb, 0x66,
	0x9b, 0xcd, 0xe2, 0x7b, 0x1f, 0x5a, 0x54, 0xee, 0x6c, 0x02, 0x31, 0xd8, 0xb0, 0xc8, 0x37, 0x72,
	0xf7, 0x3f, 0x16, 0x74, 0x45, 0x85, 0xbc, 0x8c, 0x98, 0x1c, 0xfd, 0x85, 0x71, 0xad, 0x0e, 0x51,
	0x36, 0xae, 0xbf, 0x82, 0x3d, 0x1d, 0xc1, 0xc9, 0xf9, 0x7a, 0x12, 0xe2, 0x25, 0x9e, 0xc7, 0x09,
	0xa6, 0xc3, 0x9a, 0xdc, 0xe1, 0x91, 0x57, 0x58, 0xc5, 0xd3, 0xd9, 0x79, 0xb1, 0x3e, 0x31, 0x30,
	0xe5, 0x3a, 0x9a, 0xbe, 0x25, 0x70, 0xbe, 0x84, 0xfd, 0x2d, 0xf0, 0x8a, 0x70, 0x8c, 0x8a, 0xe1,
	0xe8, 0x1e, 0x82, 0x27, 0x8a, 0x77, 0xcc, 0x03, 0xce, 0x8a, 0xa1, 0xf9, 0x93, 0x05, 0xc3, 0x82,
	0x39, 0x2a, 0x2c, 0xaf, 0x30, 0x63, 0xc1, 0x25, 0x46, 0xcf, 0x8b, 0x47, 0x79, 0xc3, 0xf0, 0x12,
	0x52, 0xf5, 0x52, 0x3d, 0xe4, 0xa4, 0x8a, 0xf3, 0x09, 0x40, 0xce, 0xac, 0xb8, 0x44, 0xb8, 0x65,
	0xf3, 0x7a, 0xa5, 0xb5, 0x0b, 0x06, 0xbe, 0x86, 0x4e, 0x66, 0xb8, 0x48, 0x71, 0x10, 0x86, 0x38,
	0xd4, 0x7e, 0x2a, 0x42, 0x24, 0x82, 0xe2, 0x45, 0xbc, 0xc4, 0xa1, 0x4e, 0xbd, 0x21, 0x65, 0x8a,
	0x64, 0xc0, 0x42, 0x3d, 0xfd, 0x0d, 0xe9, 0xfe, 0xd3, 0x82, 0xd6, 0x09, 0x5e, 0x9e, 0x45, 0xd3,
	0xab, 0x72, 0x22, 0x4b, 0xf7, 0xae, 0x11, 0xd8, 0x4c, 0x6c, 0x5c, 0x15, 0x43, 0x29, 0x40, 0x1f,
	0x41, 0x67, 0x1e, 0x90, 0xcb, 0x34, 0x10, 0x47, 0xa9, 0x2e, 0xc3, 0xb4, 0xef, 0xe9, 0x85, 0xbd,
	0x4f, 0x8d, 0x44, 0x45, 0x26, 0x47, 0x3a, 0x2f, 0xa1, 0x5f, 0x16, 0x56, 0x44, 0xe8, 0x66, 0x09,
	0x5c, 0x42, 0x5b, 0xec, 0x75, 0x82, 0x97, 0x0c, 0xfd, 0x08, 0x1a, 0x21, 0x5e, 0x9a, 0x74, 0xed,
	0x7a, 0x46, 0x20, 0x0c, 0xd2, 0x36, 0x48, 0x80, 0x73, 0x04, 0x9d, 0x8c, 0x55, 0x51, 0x3a, 0xf7,
	0xcb, 0x3b, 0xb7, 0x8d, 0x43, 0xc5, 0x7d, 0xff, 0x6d, 0xc1, 0xae, 0x58, 0x63, 0xf3, 0x40, 0x7d,
	0x04, 0xb6, 0x98, 0x92, 0xc6, 0x88, 0x07, 0x5e, 0x05, 0x48, 0x1a, 0x66, 0xca, 0x45, 0xa2, 0x45,
	0x23, 0x0c, 0xf1, 0x72, 0xa2, 0x66, 0x52, 0x4d, 0x1e, 0xa7, 0x76, 0x88, 0x97, 0xa7, 0x72, 0x2c,
	0x5d, 0x37, 0x8a, 0x9d, 0x63, 0x80, 0x7c, 0xb9, 0x0a, 0x67, 0x1e, 0x94, 0x9d, 0xe9, 0x64, 0x51,
	0x29, 0x7a, 0xf3, 0x4b, 0xe8, 0x8c, 0x31, 0x11, 0x97, 0x68, 0xc2, 0xf3, 0x46, 0x22, 0x56, 0xa9,
	0x69, 0x98, 0xb8, 0x3d, 0x89, 0xb2, 0xc0, 0x44, 0x96, 0x83, 0x34, 0xd0, 0xd0, 0xc5, 0x0a, 0xaa,
	0x97, 0x5a, 0x81, 0xe8, 0xa0, 0xfb, 0xc7, 0x0a, 0x96, 0x6d, 0x60, 0x42, 0xf5, 0x35, 0xdc, 0x62,
	0x86, 0x27, 0x1a, 0x85, 0x70, 0x49, 0x87, 0xed, 0x03, 0x6f, 0x8b, 0x92, 0x97, 0x31, 0x5e, 0xac,
	0x85, 0x23, 0x2a, 0x88, 0x03, 0x56, 0xe6, 0x3a, 0x9f, 0xc1, 0x5e, 0x15, 0xf0, 0x26, 0x6d, 0x22,
	0xdf, 0xb1, 0x10, 0x9f, 0x6f, 0x00, 0x8e, 0xa5, 0x47, 0xe2, 0x94, 0x56, 0x5e, 0xcc, 0x1d, 0x68,
	0x9b, 0xf2, 0x36, 0x83, 0xcc, 0xd0, 0xf9, 0x31, 0x6a, 0x6c, 0x39, 0x46, 0xee, 0x6f, 0xa1, 0xa9,
	0xd6, 0xcf, 0x1e, 0x61, 0x56, 0xe1, 0x11, 0xf6, 0x08, 0xfa, 0xab, 0x19, 0x2e, 0xbe, 0xb1, 0x6a,
	0xb2, 0x08, 0x7a, 0x82, 0x9b, 0x3d, 0x9f, 0x6e, 0x43, 0x33, 0x48, 0xf9, 0x2c, 0xa6, 0xfa, 0xac,
	0x6b, 0x0a, 0x3d, 0x2c, 0xdf, 0x54, 0xbb, 0x5e, 0xee, 0x89, 0xb9, 0x9d, 0x7c, 0x23, 0x2e, 0x27,
	0x32, 0x61, 0x9b, 0xe5, 0xfc, 0xb0, 0xdc, 0xe4, 0xbb, 0x87, 0x2d, 0xad, 0x9e, 0x37, 0x89, 0x87,
	0xd0, 0x53, 0x3b, 0x95, 0xaa, 0xb7, 0xab, 0x78, 0xb2, 0x80, 0xdd, 0x25, 0x34, 0xce, 0xd6, 0x49,
	0x2c, 0x2a, 0x6b, 0x45, 0x63, 0x72, 0xa9, 0xbd, 0x53, 0x84, 0xaa, 0x1e, 0x4a, 0xc5, 0xdd, 0x5b,
	0x4d, 0x50, 0x43, 0x0a, 0x97, 0xd4, 0x2e, 0x3a, 0xa4, 0x9a, 0xca, 0x86, 0x6b, 0xa3, 0x30, 0x5c,
	0x11, 0x34, 0xc4, 0x85, 0x45, 0x5e, 0x03, 0x6c, 0x5f, 0x7e, 0xbb, 0x8f, 0xa1, 0x27, 0xf6, 0x65,
	0x27, 0x01, 0x0f, 0x18, 0xe6, 0xe8, 0x2e, 0xd8, 0x5c, 0xd0, 0xda, 0x17, 0xdb, 0x13, 0x52, 0x5f,
	0xf1, 0xdc, 0xdf, 0x59, 0xd0, 0x3f, 0x5d, 0x24, 0x31, 0xe5, 0xec, 0x0b, 0x4c, 0x65, 0x67, 0x7c,
	0x2a, 0xf6, 0x4f, 0x49, 0xe6, 0xfc, 0x5d, 0xaf, 0x0c, 0x50, 0xe3, 0x5a, 0x9f, 0x64, 0x0d, 0x75,
	0x3e, 0x86, 0x6e, 0x81, 0xfd, 0xae, 0x41, 0x5d, 0x2f, 0x96, 0xd9, 0x1f, 0x2d, 0x40, 0xf9, 0x0e,
	0xa6, 0x43, 0xa2, 0x9f, 0x96, 0x7b, 0xca, 0x7d, 0xef, 0x6d, 0xcc, 0xdb, 0x2d, 0xc5, 0x39, 0xdd,
	0xd6, 0x18, 0x74, 0x7f, 0x7d, 0xaf, 0x5c, 0xf9, 0x83, 0x0d, 0xdf, 0x8a, 0x76, 0xfd, 0xd5, 0x82,
	0xdd, 0x5c, 0x9a, 0x8d, 0x5e, 0x74, 0x54, 0xec, 0xfe, 0xca, 0xb8, 0x1f, 0x78, 0x15, 0xc0, 0x6b,
	0x26, 0xc1, 0x97, 0x37, 0x98, 0x04, 0xef, 0x97, 0x2d, 0xdd, 0xad, 0xf0, 0xbf, 0x68, 0xed, 0x1f,
	0x2c, 0x70, 0x2a, 0x8c, 0x30, 0x25, 0xed, 0x41, 0x2b, 0x52, 0x52, 0x6d, 0xf2, 0x5e, 0x95, 0xc9,
	0xbe, 0x01, 0xdd, 0xa0, 0xbe, 0xcb, 0x0d, 0xba, 0xbe, 0xf1, 0x56, 0xfa, 0x35, 0xdc, 0xc9, 0x56,
	0x3d, 0xc3, 0x62, 0xd1, 0x60, 0x7e, 0x34, 0xe5, 0xd1, 0x52, 0xbf, 0x49, 0x57, 0x18, 0x5f, 0x85,
	0xc1, 0xda, 0x3c, 0x18, 0x32, 0x5a, 0xd4, 0xc9, 0x2c, 0x4e, 0xa9, 0x6a, 0xb7, 0xb6, 0xaf, 0x08,
	0x71, 0x26, 0x16, 0x31, 0xe1, 0x33, 0xd5, 0x6a, 0x6d, 0x5f, 0x53, 0xf2, 0x6c, 0x61, 0x7c, 0x65,
	0x1e, 0x43, 0x8a, 0x70, 0xff, 0x67, 0xc1, 0xfe, 0xe6, 0xa6, 0x26, 0x10, 0x2f, 0x01, 0x02, 0xc5,
	0x8a, 0xb2, 0xf4, 0x1d, 0x78, 0x5b, 0xd0, 0xde, 0x51, 0x06, 0x55, 0x39, 0x2c, 0xe8, 0x5e, 0x3f,
	0xbd, 0x10, 0x34, 0x16, 0x71, 0x98, 0xdd, 0x84, 0xc5, 0xb7, 0xf3, 0x35, 0x0c, 0x36, 0xd6, 0xab,
	0x38, 0x27, 0x4f, 0xca, 0x69, 0x77, 0xbc, 0xad, 0x61, 0x2c, 0x66, 0xff, 0x6f, 0x16, 0x0c, 0xde,
	0xee, 0x62, 0xcd, 0x19, 0x0e, 0x42, 0x4c, 0xe5, 0xf2, 0x62, 0x08, 0x9a, 0x3f, 0x43, 0xbe, 0x16,
	0xa0, 0xe7, 0x62, 0xbc, 0x11, 0x9e, 0x8d, 0x37, 0x71, 0xcc, 0x36, 0xc7, 0xf6, 0xb1, 0x06, 0x64,
	0x97, 0x73, 0x45, 0xaa, 0xcb, 0x79, 0x41, 0xf4, 0xae, 0x7f, 0x46, 0xbd, 0x82, 0xbd, 0xe7, 0x4d,
	0xf9, 0x8f, 0xee, 0xe9, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x52, 0x79, 0x2b, 0xbc, 0xaf, 0x13,
	0x00, 0x00,
}
